apiVersion: apps/v1 
kind: Deployment
metadata:
  name: planted-prod
spec:
  selector:
    matchLabels:
      app: planted-prod
  replicas: 2
  template:
    metadata:
      labels:
        app: planted-prod
    spec:
      containers:
      - name: planted-prod
        image: gcr.io/circleci-demo-286921/planted-app:v10
        ports:
        - containerPort: 80