apiVersion: apps/v1 
kind: Deployment
metadata:
  name: circleci-demo-prod
spec:
  selector:
    matchLabels:
      app: circleci-demo-prod
  replicas: 2
  template:
    metadata:
      labels:
        app: circleci-demo-prod
    spec:
      containers:
      - name: elated-lederberg
        image: gcr.io/circleci-demo-286921/rdw/circleci-demo
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: circleci-demo-prod
spec:
  type: LoadBalancer
  selector:
    app: circleci-demo-prod
  ports:
      - port: 3000